#!/usr/bin/env bash
#
# Snapshots the stateful volumes in the stack.
#
# The service itself holds nothing durable - sessions live in memory and
# restoring it means starting the container. What is worth capturing is the
# metric history and anything created in Grafana by hand.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

source "$(dirname "${BASH_SOURCE[0]}")/load-env.sh"
BACKUP_DIR="${BACKUP_DIR:-backups}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
ARCHIVE="${BACKUP_DIR}/realtime-edge-${STAMP}.tar.gz"
PROJECT="$($COMPOSE config --format json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("name","realtime-edge-demo"))' 2>/dev/null || echo realtime-edge-demo)"

mkdir -p "$BACKUP_DIR"
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

echo "backing up volumes for project '${PROJECT}'"

# Read the volumes through a throwaway container rather than from the host.
# The volume lives inside the container runtime's storage, and on macOS or in
# rootless mode it is not addressable as a host path at all.
for vol in prometheus-data grafana-data; do
  full="${PROJECT}_${vol}"
  echo "  ${full}"
  # stderr is deliberately not discarded. A backup that fails quietly is
  # indistinguishable from one that worked until the day it is needed.
  $DOCKER run --rm \
    -v "${full}:/source:ro" \
    -v "${STAGING}:/backup" \
    alpine:3.21 \
    tar czf "/backup/${vol}.tar.gz" -C /source .
done

# Configuration is in git, so it is not backed up. What is captured is the
# manifest: which image digests were running, so a restore can reproduce the
# same versions rather than whatever the tags point at later.
$COMPOSE ps --format json > "${STAGING}/running-manifest.json" 2>/dev/null || true

cat > "${STAGING}/MANIFEST.txt" <<MANIFEST
Backup taken : ${STAMP}
Project      : ${PROJECT}
Contents     : prometheus-data.tar.gz, grafana-data.tar.gz, running-manifest.json

Not included, deliberately:
  - Application configuration. It is in git; restoring it means checking out
    the matching commit.
  - Provisioned dashboards and datasources. Also in git, and reapplied on
    start-up, so a restore does not depend on this archive for them.
  - TLS certificates. Regenerated by 'make certs'; in production they are
    reissued by ACME rather than restored.

Restore with:
  make restore SNAPSHOT=<this file>
MANIFEST

tar czf "$ARCHIVE" -C "$STAGING" .

echo ""
echo "wrote ${ARCHIVE} ($(du -h "$ARCHIVE" | cut -f1))"
echo ""
echo "A backup that has never been restored is a hypothesis. Verify with:"
echo "  make restore SNAPSHOT=${ARCHIVE}"
